### ISSUE TITLE
HTTPS 설정에 대해

### ISSUE THREAD

**Issue by wcho21** [boostcampwm-2022/web27-Wabinar#106]
### 하려고 했던 일

- 사용자가 HTTP로 접근했을 때 HTTPS로 리다이렉션
- 프론트엔드 HTTPS로 static files serve
- 백엔드 HTTPS 지원

### 기존 상황

![screenshot1](https://user-images.githubusercontent.com/89635107/203257770-f1335967-119f-4b07-8a8b-6c413bc20544.png)

기존에는 단순히 서버에서 두 포트를 열어놓고 접근하게끔 했습니다.

### 시도한 것

![screenshot2](https://user-images.githubusercontent.com/89635107/203257867-160cc857-b5b5-421a-a3fd-21d815c86cb4.png)

1. http(`:80`)로 접근하면 https(`:443`)로 리다이렉션 시키는 것이랑

1. 이후 https로 접근할 때 프론트에서 리액트 빌드 파일을 제공하는 것 까지는 했습니다

근데 문제점이 있어요

- CORS 이슈
  ![screenshot4](https://user-images.githubusercontent.com/89635107/203258259-37840afa-b64c-4b1d-aaaa-d2953418d236.png)
  CORS 설정을 수정하면 되긴 하는데, 에러 메시지에서 보듯이 백엔드도 똑같이 HTTPS를 써야합니다.

- http/https schema
  백엔드는 http로 열려있어요. 그래서 FE는 https로 접근하는데 BE는 http연결을 합니다.
  백엔드도 https로 접근하게 하려면 두 가지 방법이 있는데
  - BE에서도 https 서버를 연다 (`express` 코드 상에서 해결)
  - `/api` 와 같은 url로 접근하면 BE(`:8080`)로 proxying을 한다 (`nginx` 상에서 해결)
  
nginx를 쓰고 있으니 두 번째 방법으로 하려고 합니다.
목표하는 그림은 다음처럼 됩니다.

![screenshot3](https://user-images.githubusercontent.com/89635107/203259062-7bb49d99-5ab1-486b-85d8-9ba2f2f6d0a3.png)

이렇게 하려면 프론트에서 백엔드에 요청 시 url을 수정해야 합니다.
그 주소는 환경변수에서 관리하도록 할 수 있습니다.

## 해결 방법

기존 코드를 바꾸지 않고 최대한 nginx를 써서 해결해보려고 했습니다.

아래 nginx 설정 내용은 서버에서 `/etc/nginx/site-available/default` 파일에서 볼 수 있습니다.

### 1. HTTPS 리다이렉션

```
server {
        listen 80;

        return 307 https://www.minari.shop$request_uri;
}
```

80 포트로 들어오면 `https`로 리다이렉션하게끔 307 응답을 보냅니다.

`307` 응답은 리다이렉션 시 요청 body와 method를 그대로 쓰게 해준다고 합니다. (구글이랑 네이버가 이런 응답을 보내길래 저도...)

### 2. 리액트 빌드 파일 serve & BE proxying

```
server {
        listen 443 ssl;
        server_name www.minari.shop;

        root /home/wabuser/wabinar/client/dist/;

        ssl_certificate /etc/letsencrypt/live/www.minari.shop/cert.pem;
        ssl_certificate_key /etc/letsencrypt/live/www.minari.shop/privkey.pem;

        location / {
                try_files $uri /index.html;
        }

        location /api/ {
                proxy_pass http://www.minari.shop:8080;
        }
}
```

- `location /`은 리액트 빌드 파일을 static하게 serve하는 부분이구요.

- `location /api/`는 BE로 proxying하는 부분입니다.

`ssl_certificate`, `ssl_certificate_key`는 https 사용을 위한 설정입니다.
letsencrypt로 인증서랑 키를 발급해서 `pem` 파일을 받았는데, 여기서 사용했습니다.

### 3. (추가 이슈) non-www 에서 www로 리다이렉션

`minari.shop` 으로 접근 시 `www.minari.shop` 과는 주소가 다르기 때문에 cors 이슈가 발생했습니다.

그래서 `www`가 붙어있지 않으면, nginx로 `www`가 붙은 주소로 리다이렉션 시키는 것으로 해결했습니다.

```
server {
        listen 443 ssl;
        server_name minari.shop;

        ssl_certificate /etc/letsencrypt/live/www.minari.shop/cert.pem;
        ssl_certificate_key /etc/letsencrypt/live/www.minari.shop/privkey.pem;

        return 307 https://www.minari.shop$request_uri;
}
```

위에서 처럼 접근 주소(`server_name`)가 `minari.shop`이면 리다이렉션 합니다.

### 스크린샷

![resolved](https://user-images.githubusercontent.com/89635107/203278191-d133a0c4-35ed-4179-9251-fac1e092a758.gif)

`http`로 접근시 `https`로, `www`를 안붙였을 때 `www`를 붙인 곳으로 리다이렉션합니다.

`/`에 접근시 로그인까지 되어서 `/workspace`로 넘어가요.

**Comment by se030** [comment]
문제점이 있다고 하셔서 긴장했는데 해결방법을 알려주셨네요.
왠지 도훈님이 이 이슈 읽으면 원희님 천재 아니에요?라고 하실 것 같아요.
논외로 그림이 정말 인상적이에요.

**Comment by wcho21** [comment]
@se030 그림은 생산성을 위해 그림판을 선택했어요.
글은 아직 작성중이에요. 오늘 안으로 해결하는게 목표...입니다. 해결하면 업데이트 할게요.

**Comment by wcho21** [comment]
해결 방법 부분 업데이트 했습니다.

**Comment by dohun31** [comment]
와... 원희님 천재 아니에요? nginx 뭐하는건지 전혀 몰랐는데 이거 읽으니까 바로 이해돼요.. 진짜..
minari.shop 너무 웃겨요

**Comment by se030** [comment]
정리 너무 잘해주셔서 지금 거의 자고있는데도 이해했어요
