### ISSUE TITLE
Feat : WebRTC 시그널링 소켓 서버 베이스 구축

### ISSUE THREAD

**Issue by juyeong-s** [boostcampwm-2022/web27-Wabinar#109]
## 💎 개발할 기능
- [ ] 워크스페이스 당 회의는 하나니까 namespace로 구분해줄 필요없이 room으로만 join 시켜도 될 것 같아요 ..?
- [ ] WebRTC connection on
- [ ] Room Join

**Comment by wcho21** [comment]
서버에서 별다른 유저 보관 없이 구현할 수 있었어요. 왜냐면 항상 보내는 사람이 누군지 알 수 있기 때문이에요.

```javascript
    socket.on('some_event', () => {
      const senderId = socket.id;

      socket.emit('another_event', senderId); // broadcast
    });
```

즉 소켓을 통해 A가 B에게 메시지를 전달할 때, B는 A가 누군지 `senderId` 때문에 알 수 있어요.

모듈 사용자 측인 클라이언트에서는 피어를 따로 기억해둬야 할 필요가 있는데 `senderId`를 받아서 할 수 있어요.

**Comment by juyeong-s** [comment]
> 서버에서 별다른 유저 보관 없이 구현할 수 있었어요. 왜냐면 보내는 사람이 누군지 항상 알 수 있기 때문이에요.
> 
> 
> 
> ```javascript
> 
>     socket.on('some_event', () => {
> 
>       const senderId = socket.id;
> 
> 
> 
>       socket.emit('another_event', senderId); // broadcast
> 
>     });
> 
> ```
> 
> 
> 
> 즉 소켓을 통해 A가 B에게 메시지를 전달할 때, B는 A가 누군지 `senderId` 때문에 알 수 있어요.
> 
> 
> 
> 모듈 사용자 측인 클라이언트에서는 피어를 따로 기억해둬야 할 필요가 있는데 `senderId`를 받아서 할 수 있어요.

만약 회의에 늦게 참여한 유저는 어떻게 이 전에 접속해 있던 사용자들을 받아올 수 있나요?
클라이언트에 처음 접속하면 상태가 초기화돼서 모듈에 아무것도 없지 않나요?
