### ISSUE TITLE
Refactor : 소켓 관심사 리팩토링

### ISSUE THREAD

**Issue by juyeong-s** [boostcampwm-2022/web27-Wabinar#151]
## ♻️ 리팩토링 사항

아래 사항대로 관심사를 나눠보아요~

> - workspace 네임스페이스 단위로 동작
>    - 회의 시작, 종료, 멤버 새로 참여하면 알려주기, 회의록 추가되면 알려주기, 시그널링
> - mom room 단위로 동작
>    - 회의록 수정

+ 시간되시면 @wcho21 님 의견도 알려주세요

## 📖 참고 사항

<img src="https://user-images.githubusercontent.com/63364990/204481390-bc27b786-e11d-4a13-b8dd-919e04a320bb.png" width="500"/>

**Comment by dohun31** [comment]
너무 킹받아요 ㅜㅜ
