### ISSUE TITLE
웹소켓 연결이 배포 서버에서 안됐던 이유

### ISSUE THREAD

**Issue by wcho21** [boostcampwm-2022/web27-Wabinar#162]
# 🤔 문제

## Socket.IO namespace

먼저 socket.io에서 namespace가 전달되는 방식을 봐야합니다.

```javascript
import { io } from "socket.io-client";

const socket = io("https://example.com/order");
```

위에서 `io("https://example.com/order")`은 `order`를 namespace로 서버에 전달합니다.
문법은 마치 요청 url을 바꾸는 것 같지만, namespace와 요청 url은 상관이 없습니다.

정리하면:
- 네임스페이스를 줘도 요청 url은 바뀌지 않습니다.
- namespace는 주소가 아니라 소켓 메시지 안에 담겨 서버에 전송됩니다.

## 예시: 기존 상황

아래는 namespace로 `/api/signaling`, `/api/sc-workspace`를 썼을 때의 모습입니다.

![image](https://user-images.githubusercontent.com/89635107/204687798-1dad9644-23f4-4966-8830-0a5fb9c2d7e0.png)
요청 url은 기본값인 `/socket.io`를 사용하고 있습니다.

![image](https://user-images.githubusercontent.com/89635107/204690152-4f069a1c-c2fb-43d8-bc15-9a9d684d1f0f.png)
namespace는 소켓 메시지 안에 담겨 있습니다.

## 배포 서버의 nginx

![image](https://user-images.githubusercontent.com/89635107/204689412-96ca8892-6052-4dc5-8208-e3c2dec1a0fd.png)

현재 배포 서버의 요청/응답 구조는 위처럼 되어있습니다.

여기서 `/socket.io`로 서버에 요청을 하게 되면 nginx는 FE로 보냅니다.

![image](https://user-images.githubusercontent.com/89635107/204689555-572d0531-ca4e-4474-b240-a129a6ecc6e4.png)

저희는 기존 코드에서 `io("www.minari.shop/api/signaling")`이라고 했지만, 요청 url은 그대로 `/socket.io`가 됩니다.
`/api/signaling`은 네임스페이스고 소켓 메시지 안으로 들어가니까요.

서버의 BE에서 웹소켓 연결 시도 로그도 보이지 않았던 이유입니다.

# 💡 해결

## [Socket.IO `path`](https://socket.io/docs/v4/client-options/#path)

요청 url을 바꾸는 것은 `path` 옵션에서 할 수 있습니다.

위 스크린샷에서 보여주듯이 요청 url은 기본적으로 `/socket.io`가 됩니다.
왜냐하면 `path` 옵션의 기본 값이 `/socket.io`이기 때문입니다. ([`path` 옵션 레퍼런스](https://socket.io/docs/v4/client-options/#path) 참고)

클라이언트와 서버쪽 둘 다 이 옵션을 사용해야 합니다.

```javascript
// client
import { io } from 'socket.io-client';
const socket = io(server_url, { path: '/ws' });

// server
import { Server } from 'socket.io';
const io = new Server({ path: '/ws' });
```

## nginx 수정

웹소켓 요청 url에 `/api`를 쓰면 http api와 혼동되는지 서버에서 응답이 잘 오지 않는 문제가 있었습니다.
그래서 별도 url을 사용해야 했고 `/ws`로 하였습니다.

![image](https://user-images.githubusercontent.com/89635107/204690640-b16d03ca-561a-4b89-910b-c3828383d757.png)

nginx에서는 다음과 같은 config를 추가했습니다.

```nginx
        location /ws/ {
                proxy_pass http://127.0.0.1:8080;

                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
                proxy_set_header Host $host;
        }
```

웹소켓은 `proxy_set_header`로 추가적인 헤더를 전달해야 합니다.
그 이유는:

- Upgrade와 Connection 헤더가 hop-by-hop 헤더이기 때문에 다시 붙여서 전달해야 합니다.
- Upgrade 헤더 자체는 protocol switching(여기서는 http에서 websocket)를 위해 필요합니다.

라고 요약하고 자세한 내용은 [Connection header (hop-by-hop header)](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Connection), [Upgrade header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Upgrade)를 참고하세요.

## 해결 결과

![image](https://user-images.githubusercontent.com/89635107/204692886-6d044825-af07-431c-b996-978b7e2682db.png)

![image](https://user-images.githubusercontent.com/89635107/204692996-acd7b511-6a58-47c7-8251-370319739d32.png)

이제 `/ws`로 요청이 가도록 만들었고, 실제 웹소켓 통신도 `pending`으로 유지할 수 있었습니다. (웹소켓이 여러개 연결되는 건 고쳐야할 버그네요..^^)

**Comment by se030** [comment]
기승전결에 놀라운 반전도 있는 노트네요 ...^^

**Comment by wcho21** [comment]
@se030 감사드려요 ...^^
