### ISSUE TITLE
Fix: JWT 토큰 생성 함수가 Pending promise를 리턴하는 문제

### ISSUE THREAD

**Issue by wcho21** [boostcampwm-2022/web27-Wabinar#28]
## 👨‍🔧 버그 수정 사항

아래 함수가 현재 pending promise를 리턴합니다.

https://github.com/boostcampwm-2022/web27-Wabinar/blob/d471dc0c1e131ffc8a269debcbd1c57d6e2a9b6e/server/utils/jwt.ts#L10-L19

`async`로 선언해 문제를 해결하려고 합니다.

- [ ] `async`로 선언하고 사용하는 코드에서 `await` 사용

**Comment by se030** [comment]
https://github.com/auth0/node-jsonwebtoken
jwt.sign(payload, secretOrPrivateKey, [options, callback])
(Asynchronous) If a callback is supplied, the callback is called with the err or the JWT.
(Synchronous) Returns the JsonWebToken as string

해당 함수만 테스트 했을때 promise가 반환되셨나요?
제가 postman으로 테스트 해봤을 때는 토큰이 잘 왔는데 혹시 서비스 함수 쪽에서 쪽에서 핸들링 안된 promise가 있는지 확인 부탁드려요.
문서에는 이렇게 나와있는데 옵션만 넣어도 async로 바뀌나보네요..

**Comment by wcho21** [comment]
`jwt` 모듈 문제가 아니라 테스트를 작성할 때 모킹을 `mockResolvedValue`로 해서 생기는 문제였어요.
문제가 없으므로 클로즈합니다.
