### ISSUE TITLE
버그: RTC에서 피어가 동시에 연결을 서로에게 시도하면 실패하는 이슈

### ISSUE THREAD

**Issue by wcho21** [boostcampwm-2022/web27-Wabinar#282]
## 👨‍🔧 버그 수정 사항

회의 시작 이후 접속한 유저끼리는 화상 회의가 정상적으로 진행됩니다

그런데 회의 시작 전에 접속한 유저끼리는 회의 시작 버튼을 누르면 피어의 스트림을 갖고 올 수 없는 문제가 있습니다.

![image](https://user-images.githubusercontent.com/89635107/206383858-5c897d86-067c-45b7-8be8-9f17c7b15e90.png)

## 추측한 원인

회의 시작 전에 입장해 있는 상태로 회의 시작하면 에러나는 이유가 이미 있던 사람들끼리 hello를 주고 받아서 그런것 같아요

![screenshot1](https://user-images.githubusercontent.com/89635107/207218833-40a3accd-c5b3-496b-be65-b6e75cd6713d.png)

![screenshot2](https://user-images.githubusercontent.com/89635107/207218837-0a3c98ab-ce65-4e8e-985e-0d64bee0ffe6.png)

이를 해결하기 위한 방법을 생각중입니다.

+ 생각해보니까 회의를 시작하고 나서도, 두 피어가 동시에 회의 연결을 시도하면 똑같은 문제가 발생하겠네요.

**Comment by juyeong-s** [comment]
이슈 제목 fix 로 해주세여

**Comment by wcho21** [comment]
@juyeong-s 아직 해결할지 말지 몰라서 일단 버그 내용만 작성해놨고 추후 고쳐도 될까요..^^

**Comment by wcho21** [comment]
회의 참여로 임시 방편으로 해결하긴 했는데 본질적인 해결 방법은 아닙니다. 나중에 해결 방법이 떠오르면 다시 reopen 할게요.
