### ISSUE TITLE
Refactor: Context 타입 가드 훅 리팩토링

### ISSUE THREAD

**Issue by se030** [boostcampwm-2022/web27-Wabinar#410]
## ♻️ 리팩토링 사항

- 현재 context null check를 위한 훅들이 [각각의 context마다 구현](https://github.com/boostcampwm-2022/web27-Wabinar/tree/dev/client/src/hooks/context)되어 있어요.

- 타이핑이 제대로 적용되지 않아서 중간중간 [불필요한 null check](https://github.com/boostcampwm-2022/web27-Wabinar/blob/dev/client/src/components/Mom/index.tsx#L264)도 하고있는 것 같아요.

- OAuth 페이지 쪽에서 context 훅이 [적용되지 않은 라인](https://github.com/boostcampwm-2022/web27-Wabinar/blob/dev/client/src/pages/OAuth/index.tsx#LL8C1-L8C1)도 발견했어요.

<br />

- [ ] 고차 훅을 만들어 코드 중복을 줄이고 context를 깔끔하게 사용할 수 있도록 해요.

**Comment by dohun31** [comment]
Good~

**Comment by se030** [comment]
but #409 shd be done first ...😅
