### ISSUE TITLE
Refactor: 워크스페이스 페이지 컴포넌트 구조 개선

### ISSUE THREAD

**Issue by wcho21** [boostcampwm-2022/web27-Wabinar#62]
## ♻️ 리팩토링 사항

원희님이 제안주신 이슈를 해결하기 위해 선행되어야 하는 컴포넌트 구조 리팩토링이 있었어요.
리팩토링 전 워크스페이스 페이지 구조는 아래와 같아요.

```
<WorkspaceList />
<SelectModal />
<WorkspaceModal />
```

1. WorkspaceList에서 플러스 아이콘을 클릭하면 SelectModal이 열리고,
2. SelectModal에서 선택한 메뉴의 정보로 WorkspaceModal이 열리는 동작 흐름을 가지고 있어요.
3. SelectModal, WorkspaceModal은 각각 컨테이너 외부를 클릭하면 사라져요.

<img width="552" alt="image" src="https://user-images.githubusercontent.com/63814960/202272092-3c45cecc-998a-4ed8-a052-9c6bb1c54433.png">
<img width="636" alt="image" src="https://user-images.githubusercontent.com/63814960/202272206-ade112f2-20d2-472f-a388-e2372b9e72b0.png">

사진에서 첫번째가 SelectModal, 두번째가 생성 옵션이 선택된 Workspace 모달이에요.
SelectModal, WorkspaceModal 둘 다 모달로 네이밍했는데 헷갈릴 수 있어서 첫번째 사진의 컴포넌트는 드롭다운으로 부르기로 했어요.

<br />

1️⃣ 처음에는 페이지에 있던 컴포넌트들을 WorkspaceList 안으로 옮기고 동작 흐름에 따라 계층적으로 구성해보려고 했어요.

```
WorkspaceList
- WorkspaceThumbnailList
- AddButton
- WorkspaceSelectModal
  - SelectModal (Dropdown)
  - WorkspaceCreateModal
  - WorkspaceJoinModal
```

이렇게 만든 `WorkspaceSelectModal`은 이름만 모달일 뿐 모달이 아니었고 컨트롤러? 매니저? 뭐라고 불러야 할지 모르겠는 상황이 되었어요. 다시 정리해보면 관심사 분리가 제대로 이루어지지 못했어요.

- WorkspaceList
  - WorkspaceThumbnailList
    **`모든 워크스페이스`** 썸네일 표시
    썸네일 클릭에 **`현재 선택된 워크스페이스`** 변경
  - AddButton
    클릭에 `드롭다운 isOpen` 변경
  - WorkspaceSelectModal
    - SelectModal (Dropdown)
      드롭다운 아이템 클릭에 `현재 선택된 옵션` 변경, setIsOpen(false)
    - `현재 선택된 옵션`에 따라 WorkspaceJoinModal / WorkspaceCreateModal
      각각의 모달에서 일어나는 상호작용에 따라 **`모든 워크스페이스`**, **`현재 선택된 워크스페이스`** 변경될 수 있음

<br />

2️⃣ 상호작용 추상화와 Compound Pattern이라는 개념에서 출발해 다시 분리를 시도했어요.

[토스ㅣSLASH 22 - Effective Component 지속 가능한 성장과 컴포넌트](https://www.youtube.com/watch?v=fR8tsJ2r7Eg)
[Compound Components with React Hooks](https://kentcdodds.com/blog/compound-components-with-react-hooks)

(하루 뒤에 다시 읽어주세요)

<br />

## ⚽️ 원희님이 쏘아올린 작은 공

![1](https://user-images.githubusercontent.com/89635107/202102177-2a49ce3e-7240-46e6-b007-858f2a2edcac.gif)

현재 구현한 워크스페이스 리스트 메뉴와 기획서 상에는 두 가지 차이점이 있어요

- 기획서에는 메뉴 위치가 `+` 버튼 옆에 있지만 지금은 고정되어 있음
- 기획서에는 화면 어두워짐이 없지만 현재는 어두워짐

![2](https://user-images.githubusercontent.com/89635107/202102536-f079bce7-2ac5-4265-9147-7fbb1d1f02de.png)

현재 메뉴는 워크스페이스 페이지의 관심사인데, 이걸 워크스페이스 리스트의 관심사로 옮기려고 합니다.
그러면 리스트 안에서 메뉴가 들어있기 때문에 위치 문제는 자연스럽게 해결될 것으로 보여요.

그리고 이 메뉴 컴포넌트는 기존에 모달과는 다른 컴포넌트로 분리하려고 해요.
그렇게 하면 화면이 어두워지는 부분은 사라질 것으로 생각해요.

- [X] 워크스페이스 리스트 메뉴 위치를 `+` 옆으로 이동
- [X] 화면 어두워짐 없애기

**Comment by se030** [comment]
unassign 잘못했어요 ㅠㅠ 메뉴 위치 외에도 수정할 것들이 있어서 이슈 내용에 추가할게요

**Comment by juyeong-s** [comment]
화면 어두워짐 없애려고 하셨군요 사실 기획서 상에는 없지만 모달 바깥 영역을 누르면 선택 모달이 닫혀야 될 거 같은데 어두운 배경을 안주니까 어색하더라고요 그래서 넣었는데 없애는 것도 좋아요
