### ISSUE TITLE
Feat: 텍스트 복사 버튼 만들기

### ISSUE THREAD

**Issue by dohun31** [boostcampwm-2022/web27-Wabinar#98]
## 💎 개발할 기능

- [ ] 클릭 시 target text를 클립보드에 복사한다.

## 📖 참고 사항
`참여코드를 확인한다.` 까지 하려고 했는데 아직 API가 없어서 나중에 하려고 해요.

**Comment by se030** [comment]
참여코드를 확인한다. 까지 하려고 했는데 아직 API가 없어서 나중에 하려고 해요.
